### ISSUE TITLE
go module git.apache.org/thrift.git fails to download (getting-started)

### ISSUE THREAD

**Issue by Oblynx** [operator-framework/getting-started#52]
Following the getting started instructions fails when the thrift go module fails to download.

`$ operator-sdk new memcached-operator` looks for a series of go modules, and after some time I get
```
go: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/kosamara/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements
Error: failed to exec []string{"go", "build", "./..."}: exit status 1
```

Related to https://github.com/scottleedavis/mattermost-plugin-remind/issues/165
Suggested fix https://github.com/kubernetes/minikube/issues/5245

**Comment by davidovich** [comment]
As a workaround, in go < 1.13, setting a proxy could allow getting the module. Can you try?
```
GOPROXY=https://proxy.golang.org operator-sdk new memcached-operator
```

**Comment by camilamacedo86** [comment]
Thank you for raising it. 

To solve it you can add the proxy, and/or use the master branch and the command 'make tidy' which will use the proxy and your replicate the dep as `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0`. For more info see here: https://github.com/operator-framework/operator-sdk/issues/1873

Since it is duplicated we are closing this one. But please, feel free to re-open if you wish.
